name: CI-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install tesseract
      run: sudo apt install tesseract-ocr
    - name: install imagemagick
      run: sudo apt install imagemagick
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: create docker file
      run: ./gradlew dockerCreateDockerfile
    - name: Publish Docker image to GitHub Package Registry
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: ${{ github.event.repository.name }}
        DOCKERFILE_PATH: 'build/docker/Dockerfile'
        BUILD_CONTEXT: 'build/docker'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Show outputs of previous step
      run: |
        echo "The name:tag of the Docker Image is: $VAR1"
        echo "The docker image is hosted at $VAR2"
      env:
        VAR1: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
        VAR2: ${{ steps.docker.outputs.IMAGE_URL }}
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ github.event.repository.name }}
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
