name: CI-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install tesseract
      run: sudo apt install tesseract-ocr
    - name: install imagemagick
      run: sudo apt install imagemagick
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: create docker file
      run: ./gradlew dockerCreateDockerfile
    - name: Publish Docker image to GitHub Package Registry
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'pikture2text'
        DOCKERFILE_PATH: 'build/docker/Dockerfile'
        BUILD_CONTEXT: '/app'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Show outputs of previous step
      run: |
        echo "The name:tag of the Docker Image is: $VAR1"
        echo "The docker image is hosted at $VAR2"
      env:
        VAR1: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
        VAR2: ${{ steps.docker.outputs.IMAGE_URL }}
